@startuml

title Add lab from Student and give result
autonumber

actor "Student" as student order 0
participant "Gateway" as gw order 10
participant "DataService" as dataSvc order 30
participant "UserService" as userSvc order 20
participant "PlagiatismService" as plagSvc order 40
database "FilesDb" as filesDb order 50

activate student

student -> gw: Add lab
activate gw

gw -> dataSvc: Add lab in storage
activate dataSvc

dataSvc -> filesDb: Extract zip
activate filesDb
dataSvc -> dataSvc: Create token and rename directory
dataSvc -> gw: Give token

gw -> userSvc: Add lab with token to necessary directory
activate userSvc
userSvc -> dataSvc: Add lab with token to necessary directory

dataSvc -> filesDb: Copy files to to necessary directory
dataSvc -> userSvc: Send new name of directory
deactivate dataSvc

userSvc -> plagSvc: Check files for this lab
activate plagSvc
plagSvc -> filesDb: Check on plagiatism
plagSvc -> userSvc: Return result of the check
deactivate plagSvc

userSvc -> gw: Return result
deactivate userSvc

gw -> student: Return result
deactivate gw
deactivate student


@enduml